/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Logica.IControlador;
import Logica.Categoria;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.Enumeration;
import javax.swing.JOptionPane;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

public class InterAltaCategoria extends javax.swing.JInternalFrame {
    private final IControlador ic;
    /**
     * Creates new form InterAltaCategoria
     */
    public InterAltaCategoria(IControlador ic) {
        this.ic = ic;
        this.setTitle("Alta de Categoria");
        initComponents();
        DefaultTreeModel modeloArbol = new DefaultTreeModel(UtilArbol.construirArbolCategorias(ic.getRaizArbolCat()));
        
        this.ArbolDeCategorias.setModel(modeloArbol);
        this.ArbolDeCategorias.expandRow(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloAltCat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArbolDeCategorias = new javax.swing.JTree();
        LabelNombreCat = new javax.swing.JLabel();
        LabelPadreCat = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        textoNombreCat = new javax.swing.JTextField();
        textoPadreCat = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setVisible(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTituloAltCat.setText("Ingrese una Nueva Categoria de Espectaculo:");
        getContentPane().add(labelTituloAltCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 15, -1, -1));

        jScrollPane1.setViewportView(ArbolDeCategorias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 179, 234, 149));

        LabelNombreCat.setText("Nombre Categoria");
        getContentPane().add(LabelNombreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 74, -1, -1));

        LabelPadreCat.setText("Padre de la Categoria (opcional)");
        getContentPane().add(LabelPadreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 131, -1, 30));

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 283, -1, -1));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 283, -1, -1));

        textoNombreCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreCatActionPerformed(evt);
            }
        });
        getContentPane().add(textoNombreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 69, 189, -1));

        textoPadreCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPadreCatActionPerformed(evt);
            }
        });
        getContentPane().add(textoPadreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 133, 189, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:´
       String nuevaCat = textoNombreCat.getText().trim();
       String padre = textoPadreCat.getText().trim(); //.trim() elimina espacios en blanco antes y al final del String
       
       if(nuevaCat.isBlank()){
        JOptionPane.showMessageDialog(this, "Opcion nombre Categoria no puede ser nula!", "Error", HEIGHT);
        return;
       }
       int error;
       
       if(padre.isBlank()){ //este if hace que no tenga que repetir para mensajes de errores
           error = ic.altaCategoria(nuevaCat); //Alta con la raiz "Categoria"
       }else{
           error = ic.altaCategoria(nuevaCat, padre); //Alta con la categoria padre ingresada
       }
       
       if(error==0){
        JOptionPane.showMessageDialog(this, "Categoria ingresada con exito!", "Alta Categoria",JOptionPane.INFORMATION_MESSAGE);
        DefaultMutableTreeNode raiz = ic.getRaizArbolCat();
        ArbolDeCategorias.setModel(new DefaultTreeModel(raiz)); //Recargo el JTree siempre que se 
        //ingresa una Categoria
        return;
       }
       if(error == -1){
           JOptionPane.showMessageDialog(this, "Padre de Categoria no existe", "Error", HEIGHT);
           return;
       }
       if(error == -2){
        JOptionPane.showMessageDialog(this, "Categoria " +nuevaCat+ " ya existe en el Sistema", "Error", HEIGHT);
        return;
       }
           
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void textoNombreCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreCatActionPerformed
        // TODO add your handling code here:

        //System.out.println(nickname);
    }//GEN-LAST:event_textoNombreCatActionPerformed
    
    private void textoPadreCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPadreCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPadreCatActionPerformed
    private void limpiarFormulario() {
        textoNombreCat.setText("");
        textoPadreCat.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree ArbolDeCategorias;
    private javax.swing.JLabel LabelNombreCat;
    private javax.swing.JLabel LabelPadreCat;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTituloAltCat;
    private javax.swing.JTextField textoNombreCat;
    private javax.swing.JTextField textoPadreCat;
    // End of variables declaration//GEN-END:variables
}
