/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Logica.IControlador;
import Logica.Categoria;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.Enumeration;
import javax.swing.JOptionPane;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

public class InterAltaCategoria extends javax.swing.JInternalFrame {
    private final IControlador ic;
    /**
     * Creates new form InterAltaCategoria
     */
    public InterAltaCategoria(IControlador ic) {
        this.ic = ic;
        this.setTitle("Alta de Categoria");
        initComponents();
        DefaultMutableTreeNode nodoRaiz = ic.getRaizArbolCat();
        DefaultTreeModel modeloArbol = new DefaultTreeModel(nodoRaiz);
        
        this.ArbolDeCategorias.setModel(modeloArbol);
        this.ArbolDeCategorias.expandRow(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloAltCat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArbolDeCategorias = new javax.swing.JTree();
        LabelNombreCat = new javax.swing.JLabel();
        LabelPadreCat = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        textoNombreCat = new javax.swing.JTextField();
        textoPadreCat = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(false);

        labelTituloAltCat.setText("Ingrese una Nueva Categoria de Espectaculo:");

        jScrollPane1.setViewportView(ArbolDeCategorias);

        LabelNombreCat.setText("Nombre Categoria");

        LabelPadreCat.setText("Padre de la Categoria (opcional)");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        textoNombreCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreCatActionPerformed(evt);
            }
        });

        textoPadreCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPadreCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPadreCat)
                            .addComponent(LabelNombreCat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoPadreCat, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(textoNombreCat)))
                    .addComponent(labelTituloAltCat))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelTituloAltCat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombreCat)
                    .addComponent(textoNombreCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPadreCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPadreCat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAceptar)
                            .addComponent(botonCancelar))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
        this.dispose(); // el .trim, tiene en cuenta los \n tambien llamados "enter"?
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:´
       String nuevaCat = textoNombreCat.getText().trim();
       String padre = textoPadreCat.getText().trim(); //.trim() elimina espacios en blanco antes y al final del String
       
       if(nuevaCat.isBlank()){
        JOptionPane.showMessageDialog(this, "Opcion nombre Categoria no puede ser nula!", "Error", HEIGHT);
        return;
       }
       int error;
       
       if(padre.isBlank()){ //este if hace que no tenga que repetir para mensajes de errores
           error = ic.altaCategoria(nuevaCat); //Alta con la raiz "Categoria"
       }else{
           error = ic.altaCategoria(nuevaCat, padre); //Alta con la categoria padre ingresada
       }
       
       if(error==0){
        JOptionPane.showMessageDialog(this, "Categoria ingresada con exito!", "Alta Categoria",JOptionPane.INFORMATION_MESSAGE);
        DefaultMutableTreeNode raiz = ic.getRaizArbolCat();
        ArbolDeCategorias.setModel(new DefaultTreeModel(raiz)); //Recargo el JTree siempre que se 
        //ingresa una Categoria
        return;
       }
       if(error == -1){
           JOptionPane.showMessageDialog(this, "Padre de Categoria no existe", "Error", HEIGHT);
           return;
       }
       if(error == -2){
        JOptionPane.showMessageDialog(this, "Categoria " +nuevaCat+ " ya existe en el Sistema", "Error", HEIGHT);
        return;
       }
           
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void textoNombreCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreCatActionPerformed
        // TODO add your handling code here:

        //System.out.println(nickname);
    }//GEN-LAST:event_textoNombreCatActionPerformed
    
    private void textoPadreCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPadreCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPadreCatActionPerformed
    private void limpiarFormulario() {
        textoNombreCat.setText("");
        textoPadreCat.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree ArbolDeCategorias;
    private javax.swing.JLabel LabelNombreCat;
    private javax.swing.JLabel LabelPadreCat;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTituloAltCat;
    private javax.swing.JTextField textoNombreCat;
    private javax.swing.JTextField textoPadreCat;
    // End of variables declaration//GEN-END:variables
}
