/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Logica.IControlador;
import Logica.DataProponente;
import Logica.DataPropuesta;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class InterConsultaPerfilProponente extends javax.swing.JInternalFrame {
    private final IControlador ic;
    private List<String> listaProponentes; //Solo tiene los NickNames de los Proponentes para llenar el comboBox
    private DataProponente miProponente; //Guarda el proponente(DataProponente) del que se estan mostrando los datos en el momento
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form InterConsultaPerfilProponente
     */
    public InterConsultaPerfilProponente(IControlador ic) {
        this.setTitle("Consulta Perfil Proponente");
        this.ic = ic;
        listaProponentes = ic.getUsuariosProponentes();
        initComponents();
        for(String s : listaProponentes){
            PropoCombo.addItem(s);
        }
        String[] encabezados = {"Nickname Proveedor","Titulo Propuesta", "Lugar" , "Dinero Recaudado", "Estado Actual","Colaboradores de Propuesta"};    
    
        modeloTabla = new DefaultTableModel(encabezados,0);
        tablaPropuestasDe.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PropoCombo = new javax.swing.JComboBox<>();
        imagenPerfil = new javax.swing.JLabel();
        labelNickname = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelFecNac = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelSitioWeb = new javax.swing.JLabel();
        labelBiografia = new javax.swing.JLabel();
        jScrollPaneBio = new javax.swing.JScrollPane();
        textoBiografia = new javax.swing.JTextArea();
        textoSitioWeb = new javax.swing.JTextField();
        textoDirecc = new javax.swing.JTextField();
        textoFechaNac = new javax.swing.JTextField();
        textoEmail = new javax.swing.JTextField();
        textoApellido = new javax.swing.JTextField();
        textoNombre = new javax.swing.JTextField();
        textoNickname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPropuestasDe = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccione el Usuario Proponente a consultar:");

        PropoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--" }));
        PropoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PropoComboActionPerformed(evt);
            }
        });

        imagenPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelNickname.setText("Nickname");

        labelNombre.setText("Nombre");

        labelApellido.setText("Apellido");

        labelEmail.setText("E-mail");

        labelFecNac.setText("Fecha Nacimiento");

        labelDireccion.setText("Direccion");

        labelSitioWeb.setText("Sitio Web");

        labelBiografia.setText("Biografia");

        textoBiografia.setEditable(false);
        textoBiografia.setColumns(20);
        textoBiografia.setRows(5);
        textoBiografia.setEnabled(false);
        jScrollPaneBio.setViewportView(textoBiografia);

        textoSitioWeb.setEditable(false);
        textoSitioWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSitioWebActionPerformed(evt);
            }
        });

        textoDirecc.setEditable(false);
        textoDirecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDireccActionPerformed(evt);
            }
        });

        textoFechaNac.setEditable(false);
        textoFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFechaNacActionPerformed(evt);
            }
        });

        textoEmail.setEditable(false);
        textoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEmailActionPerformed(evt);
            }
        });

        textoApellido.setEditable(false);
        textoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApellidoActionPerformed(evt);
            }
        });

        textoNombre.setEditable(false);
        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });

        textoNickname.setEditable(false);
        textoNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNicknameActionPerformed(evt);
            }
        });

        jLabel2.setText("Lista de Propuestas:");

        tablaPropuestasDe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NickName Proponente", "Titulo Propuesta", "Lugar", "Dinero Recaudado", "Estado Actual"
            }
        ));
        jScrollPane2.setViewportView(tablaPropuestasDe);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PropoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imagenPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNickname)
                                            .addComponent(labelNombre)
                                            .addComponent(labelApellido))
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textoNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(textoNombre)
                                            .addComponent(textoApellido)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelEmail)
                                            .addComponent(labelFecNac)
                                            .addComponent(labelDireccion)
                                            .addComponent(labelSitioWeb)
                                            .addComponent(labelBiografia))
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPaneBio, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(textoFechaNac)
                                            .addComponent(textoDirecc)
                                            .addComponent(textoSitioWeb)
                                            .addComponent(textoEmail)))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(PropoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNickname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFecNac))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoDirecc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDireccion))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSitioWeb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneBio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBiografia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imagenPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNicknameActionPerformed
        // TODO add your handling code here:

        //System.out.println(nickname);
    }//GEN-LAST:event_textoNicknameActionPerformed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreActionPerformed

    private void textoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoApellidoActionPerformed

    private void textoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEmailActionPerformed

    private void textoFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoFechaNacActionPerformed

    private void textoDireccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDireccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDireccActionPerformed

    private void textoSitioWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSitioWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoSitioWebActionPerformed

    private void PropoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PropoComboActionPerformed
        int selectedItem = PropoCombo.getSelectedIndex();
        if(selectedItem != 0){ //Si entra a este if se selecciono un Usuario Proponente por lo que tengo que mostrar los datos supongo que hare una funcion por fuera
            //asi evito llenar de tanta cosa el actionPerformed
            this.miProponente = ic.consultaDeProponente((String)PropoCombo.getSelectedItem()); //Le pido al controlador que me devuelva el DataProponente del seleccionado
            //System.out.println("1Direc: " + miProponente.getDireccion() + "2SitioWeb: " + miProponente.getSitioWeb() + "3Bio: " + miProponente.getBiografia());

            llenarFormulario();
        }else{ //en el caso del else debo limpiar los datos mostrados
            limpiarFormulario();
        }
    }//GEN-LAST:event_PropoComboActionPerformed
    private void llenarFormulario(){ //Esta sera la funcion principal de este internalFrame donde lleno el formulario con las cosas ingresadas
        textoNickname.setText(miProponente.getNickname());
        textoNombre.setText(miProponente.getNombre());
        textoApellido.setText(miProponente.getApellido());
        textoEmail.setText(miProponente.getEmail());
        textoFechaNac.setText(miProponente.getFecNac().toString()); 
        
        
        ImageIcon icon = new ImageIcon(miProponente.getImagen());
        Image imagenEscalada = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);  //cambiar width a 200 y height 200
        imagenPerfil.setIcon(new ImageIcon(imagenEscalada));
       
        
        //Aprovecho a dejarme algunas cosas separadas asi reciclo codigo para el Consulta Perfil Colaborador
        textoDirecc.setText(miProponente.getDireccion());
        textoSitioWeb.setText(miProponente.getSitioWeb());
        textoBiografia.setText(miProponente.getBiografia());
        
        //IMPORTANTE Falta lista de Propuestas de este Proponente
        
        modeloTabla.setRowCount(0); //La vacio por el caso que pase de un colaborador a otro sin vaciarse al pasar por "-Seleccionar-"
        Object[] fila;
        for (DataPropuesta dataProp : miProponente.getPropuestas()){
            fila = new Object[5];
            fila[0] = "";
            fila[1] = dataProp.getTitulo(); //Por ahora solo obtengo estos datos pq ando pensando si necesitare crear otro DataType ya que me faltan datos
            fila[2] = dataProp.getLugar();
            fila[3] = "0";
            fila[4] = dataProp.getEstadoActual();
            //Fila[5]?? Que hago con esta parte que tiene una lista de Colaboradores de esta propuesta podria usar un comboBox y que si se seleccione agregue tuplas o algo 
            modeloTabla.addRow(fila);
        }
        //Lo mas complicado de pensar de eso es en que cada propuesta a su vez tiene una lista
        //de colaboradores -(parece q se puede hacer con comboBox)
    }
    private void limpiarFormulario(){ //Vacio el formualario cuando se selecciona el indice 0
        textoNickname.setText("");
        textoNombre.setText("");
        textoApellido.setText("");
        textoEmail.setText("");
        textoFechaNac.setText("");
        imagenPerfil.setIcon(null);
        //Aprovecho a dejarme algunas cosas separadas asi reciclo codigo para el Consulta Perfil Colaborador
        textoDirecc.setText("");
        textoSitioWeb.setText("");
        textoBiografia.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PropoCombo;
    private javax.swing.JLabel imagenPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneBio;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelBiografia;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFecNac;
    private javax.swing.JLabel labelNickname;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSitioWeb;
    private javax.swing.JTable tablaPropuestasDe;
    private javax.swing.JTextField textoApellido;
    private javax.swing.JTextArea textoBiografia;
    private javax.swing.JTextField textoDirecc;
    private javax.swing.JTextField textoEmail;
    private javax.swing.JTextField textoFechaNac;
    private javax.swing.JTextField textoNickname;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoSitioWeb;
    // End of variables declaration//GEN-END:variables
}
