/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Logica.IControlador;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mafiu
 */
public class InterDejarSeguir extends javax.swing.JInternalFrame {

    private final IControlador ic;
    List<String> listaUsuarios;
    /**
     * Creates new form InterDejarSeguir
     * @param ic
     */
    public InterDejarSeguir(IControlador ic) {
        this.ic = ic;
        initComponents();
        listaUsuarios = ic.getUsuarios();
        for(String s : listaUsuarios){
            comboSeguidor.addItem(s);
        }
        this.setTitle("Dejar de Seguir Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelSeguidor = new javax.swing.JLabel();
        comboSeguidor = new javax.swing.JComboBox<>();
        labelDejarSeguir = new javax.swing.JLabel();
        botonElegir = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        textDejarSeguir = new javax.swing.JLabel();

        labelTitulo.setText("Elegir usuario seguidor y usuario a dejar de seguir");

        labelSeguidor.setText("Seguidor");

        comboSeguidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--" }));
        comboSeguidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeguidorActionPerformed(evt);
            }
        });

        labelDejarSeguir.setText("Dejar de Seguir");

        botonElegir.setText("Elegir");
        botonElegir.setEnabled(false);
        botonElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElegirActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        textDejarSeguir.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(labelTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboSeguidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelSeguidor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDejarSeguir)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonElegir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textDejarSeguir)))))
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSeguidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboSeguidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelDejarSeguir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonElegir)
                    .addComponent(textDejarSeguir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElegirActionPerformed
        // TODO add your handling code here:
        int indice = comboSeguidor.getSelectedIndex();
        String seguidor = comboSeguidor.getItemAt(indice);
        InterDejarSeguirElegir IDSE = new InterDejarSeguirElegir(this.ic, seguidor, this);
        
        int x = (getParent().getWidth() - IDSE.getWidth())/2;
        int y = (getParent().getHeight() - IDSE.getHeight())/2;
        IDSE.setLocation(x, y+200);
        
        getParent().add(IDSE);
        IDSE.show();
    }//GEN-LAST:event_botonElegirActionPerformed

    
    private void comboSeguidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeguidorActionPerformed
        // TODO add your handling code here:
        int seleccion = comboSeguidor.getSelectedIndex();
        if(seleccion != 0){
            botonElegir.setEnabled(true);
        }else{
            botonElegir.setEnabled(false);
        }
    }//GEN-LAST:event_comboSeguidorActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        int seleccion = comboSeguidor.getSelectedIndex();
        if(seleccion == 0){
            JOptionPane.showMessageDialog(this, "Seleccione un usuario!", "Error", HEIGHT);
        }else{
            String nick2 = textDejarSeguir.getText();
            if(nick2.equals("---")){
                JOptionPane.showMessageDialog(this, "Elija a quien dejar de seguir!", "Error", HEIGHT);
            }else{
                String nick1 = comboSeguidor.getItemAt(seleccion);
                ic.dejarSeguirUsuario(nick1, nick2);
                JOptionPane.showMessageDialog(this, "Usuario ha dejado de seguir a " + nick2 + "!", "Listo!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_botonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonElegir;
    private javax.swing.JComboBox<String> comboSeguidor;
    private javax.swing.JLabel labelDejarSeguir;
    private javax.swing.JLabel labelSeguidor;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel textDejarSeguir;
    // End of variables declaration//GEN-END:variables

    public void cambiarTxtDejarSeguir(String txt) {
        textDejarSeguir.setText(txt);
    }
}
