/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Logica.IControlador;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;

public class InterAltaCategoria extends javax.swing.JInternalFrame {
    private final IControlador ic;
    /**
     * Creates new form InterAltaCategoria
     */
    public InterAltaCategoria(IControlador ic) {
        this.ic = ic;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        labelTituloAltCat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArbolCategorias = new javax.swing.JTree();
        LabelNombreCat = new javax.swing.JLabel();
        LabelPadreCat = new javax.swing.JLabel();
        botonAceptar1 = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        textoNombreCat = new javax.swing.JTextField();
        textoPadreCat = new javax.swing.JTextField();

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(false);

        labelTituloAltCat.setText("Ingrese una Nueva Categoria de Espectaculo:");

        jScrollPane1.setViewportView(ArbolCategorias);

        LabelNombreCat.setText("Nombre Categoria");

        LabelPadreCat.setText("Padre de la Categoria (opcional)");

        botonAceptar1.setText("Aceptar");
        botonAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptar1ActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        textoNombreCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreCatActionPerformed(evt);
            }
        });

        textoPadreCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPadreCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPadreCat)
                            .addComponent(LabelNombreCat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoPadreCat, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(textoNombreCat)))
                    .addComponent(labelTituloAltCat))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(botonAceptar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelTituloAltCat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombreCat)
                    .addComponent(textoNombreCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPadreCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPadreCat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAceptar1)
                            .addComponent(botonCancelar))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
       String nuevaCat = textoNombreCat.getText();
       String padre = textoPadreCat.getText();
       
       if(nuevaCat.equals("")){
        JOptionPane.showMessageDialog(this, "Opcion nombre Categoria no puede ser vacias!", "Error", HEIGHT);
       }
       
       

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptar1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonAceptar1ActionPerformed

    private void textoNombreCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreCatActionPerformed
        // TODO add your handling code here:

        //System.out.println(nickname);
    }//GEN-LAST:event_textoNombreCatActionPerformed

    private void textoPadreCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPadreCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPadreCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree ArbolCategorias;
    private javax.swing.JLabel LabelNombreCat;
    private javax.swing.JLabel LabelPadreCat;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAceptar1;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTituloAltCat;
    private javax.swing.JTextField textoNombreCat;
    private javax.swing.JTextField textoPadreCat;
    // End of variables declaration//GEN-END:variables
}
